### ISSUE TITLE
IK constraint stretch / creep / drift in scene view

### ISSUE THREAD

**Issue by lachsinc** [OurMachinery/themachinery-public#1358]
- **Version:** Git Master Branch
- **OS:** Windows

Video better explains so feel free to skip below..

IK, or rather the rigged mesh gets stretched out in the scene view, with the error growing and accelerating with time.
Sometimes takes a while for the issue to occur, though I *think* I've eventually seen it whenever I've had entity open for a while.
Not an issue at all in preview/simulation.
Enabling/Disabling constraint, moving constraint around etc. does not change anything.

Worth noting the entity contains:
- Sub-entity w/ an asm (the constrained entity)
- 2x IKs transforming different bones of the same rig

~~I will see if I can put together a minimal repro file~~ **See below**

https://user-images.githubusercontent.com/1400236/170732825-b036de24-51f6-4059-98f0-6d36e5f41302.mp4

**Comment by lachsinc** [comment]
Occurs with the following in both master and 2022.4:
[ik-stretch-repro.zip](https://github.com/OurMachinery/themachinery-public/files/8788154/ik-stretch-repro.zip)

Sometimes you have to be patient.. Moving the 'ik' entity (is itself the ik goal) then undoing repeatedly might encourage it to start (or that's just a coincidence lol).

**Comment by Hoogin** [comment]
I had this issue if I didn't apply any animation to my character, the IK would drift over time. So I used the simple animation component and assigned an animation. I could then work with on the IK without it drifting.

**Comment by niklas-ourmachinery** [comment]
That makes sense... the IK expects to adjust an underlying animated position. If there is no underlying animation, the IK will be applied to the last IK result again and again. A small numerical error in the IK computations can then grow, which can cause drifting.

I believe it should be possible to fix this by renormalizing the quaternions in the IK computations. Most likely, what happens is that as the error grows, the matrices become denormalized which causes the distortions.

(It is also possible that errors can grow in other ways which wouldn't be fixed by renormalization. For example, if there is a loop in the IK constraints -- bone A is constrained against bone B and bone B is constrained against bone A -- errors could grow in that loop. But the most likely issue is denormalization.)

**Comment by lachsinc** [comment]
This seems to have partially fixed the issue - the mesh no longer appears to "stretch".
However it looks like "rotation" errors are still being accumulated though if that makes any sense..

https://user-images.githubusercontent.com/1400236/173524211-e064c6e2-3a31-4e41-a897-b137a576e2b9.mp4

**Comment by niklas-ourmachinery** [comment]
That totally makes sense and I don't think that's an error.

IK constraints (depending on how they are set up) typically have some degrees of freedom. I.e. there are some axes of rotation that the constraint doesn't "care" about. If there is a rotation on one of those axes, the IK constraint won't correct it.

When an IK constraint is applied recursively against itself, some "drifting" can occur along those axes because if numerical errors creep in there is no way for the constraint to "correct" it (in the view of the constraint, one rotation is not more correct than any other).

This can be fixed by having an underlying animation that resets a fixed pose every frame before the IK constraint is applied.

Will close this as fixed.
