### ISSUE TITLE
Poll Key Event Node does not show 'e' or 'r' keys 

### ISSUE THREAD

**Issue by xenobrain** [OurMachinery/themachinery-public#891]
![Screenshot_20211201_093223](https://user-images.githubusercontent.com/1247848/144302731-8851dfc5-5f9f-42ea-b0dd-5813105ae73f.png)

**Comment by niklas-ourmachinery** [comment]
This happens because all these keys match `E` so the actual `E` is truncated of the list. I think there are multiple things that should be fixed here:

* The matching algorithm should score `E` as the best match for `E`.
* The dropdown menu should indicate that it has been truncated.
* Maybe the dropdown menu should scroll so that it can show more options (I think we still need truncation though, because there is no point in being able to scroll through >1000 options)

**Comment by niklas-ourmachinery** [comment]
Related to #46

**Comment by simon-ourmachinery** [comment]
Related #703

**Comment by frank-ourmachinery** [comment]
The problem with `E` not showing up was that the pattern matching algorithm wasn't discarding the worst match when it reached the buffer limit, but rather it would assume that the cached worst was the worst which wasn't always the case. This should be fixed for the 2022.1 release.

The other issues like the dropdown not showing that it has been truncated still exist.
![image](https://user-images.githubusercontent.com/70658773/151341079-488770dd-deab-4032-ae13-ee1b66c758f4.png)

**Comment by frank-ourmachinery** [comment]
The popup item pickers (dropdowns with textedit control) have been unified in master and scrolling behaviour has been added with the arrow keys. I don't think we want to add a scrollbar as it might encourage scrolling through> 1000 items. So instead I have added little triangle indicators to show that the user can scroll in a popup item picker.

https://user-images.githubusercontent.com/70658773/171559346-a6efcf09-f9bc-4230-8ab8-f9201ad869e9.mp4
